export default [
  {
    video_id: "L0gKPnuGLgc",
    title:
      "Secret Details Of AJ Lee's SHOCKING New WWE Contract Revealed...😨 #wwe",
    author: "TheSportsEntertainer",
    number_of_views: 311189,
    video_length: "SHORTS",
    description:
      "Secret Details Of AJ Lee's SHOCKING New WWE Contract Revealed...   #wwe Secret details of AJ Lee's shocking new WWE ...",
    is_live_content: null,
    published_time: "5 days ago",
    channel_id: "UCPFYcLD2Po64A5fyq6WRwlA",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/L0gKPnuGLgc/hq720.jpg?sqp=-oaymwE2COgCEMoBSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARg-IEYofzAP&rs=AOn4CLDKFiqnTlCcqbOa7IJ6hAZpLcNbfA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/L0gKPnuGLgc/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARg-IEYofzAP&rs=AOn4CLBDiOND6zgM0mTEBSnxqITAn63XdA",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "YNhHjOuCo1w",
    title:
      "September 2025 Energy Update: Lee Harris | Will You Let Yourself Be New?",
    author: "LeeHarrisEnergy",
    number_of_views: 352338,
    video_length: "32:41",
    description:
      "Hello everyone, The September #EnergyUpdate has arrived, and month brings a powerful wave of energy that will ripple across ...",
    is_live_content: null,
    published_time: "11 days ago",
    channel_id: "UChi8D8p41lA7ng4alum6J5Q",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/YNhHjOuCo1w/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7f7T8EgR1HIYguo5t5i4m5Zdpww",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/YNhHjOuCo1w/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXJnreJ6kBqOygudVETAXhZzIn3g",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "idEAABFzpfg",
    title: "iPhone 17/Pro/Air Impressions: Spot the Red Flags!",
    author: "Marques Brownlee",
    number_of_views: 10308001,
    video_length: "14:50",
    description:
      "Everything new from Apple's 2025 September event Keep your smartphone charged up with Ridge and get 10% off at ...",
    is_live_content: null,
    published_time: "2 days ago",
    channel_id: "UCBJycsmduvYEL83R_U4JriQ",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/idEAABFzpfg/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKzJPCxDsdU8-1inyLenyy6x_pzA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/idEAABFzpfg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA-DsRawriQWB_2y_QVhZTE81CBhA",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "D3X4Ydm-MD0",
    title: "AJ Lee returns to WWE after a decade | WWE SmackDown | 9/5/25",
    author: "WWE on Netflix",
    number_of_views: 1197496,
    video_length: "7:34",
    description:
      "AJ Lee attacks Becky Lynch in her return to WWE after retiring 10 years ago.",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UClO9oAku51INqqCVr4Xh7DQ",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/D3X4Ydm-MD0/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB1GBu3pdwH0E8TTECfgAhZ0Sg04g",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/D3X4Ydm-MD0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAA3rNGc2InnHeHKRmrIIaI2eC1Ew",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "SOCxm4nqJQE",
    title:
      "FULL SEGMENT: AJ Lee makes EPIC RETURN to combat Becky Lynch: SmackDown, Sept. 5, 2025",
    author: "WWE",
    number_of_views: 5433746,
    video_length: "16:18",
    description:
      "CM Punk calls in an ally in the form of a returning AJ Lee to combat Women's Intercontinental Champion Becky Lynch and World ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCJ5v_MCY6GNUBTO8-D3XoAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/SOCxm4nqJQE/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCOwFNIpBLIhk0v-PPYBaEuzyOWMg",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/SOCxm4nqJQE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCK18dBfnAmROxKDRZtiyB5lgRTHg",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "DVeUoCsIEcc",
    title:
      "AJ Lee and CM Punk soak in emotional return: SmackDown exclusive, Sept. 5, 2025",
    author: "WWE",
    number_of_views: 2152484,
    video_length: "5:41",
    description:
      "Moments after SmackDown goes off the air, AJ Lee and CM Punk celebrate Lee's emotional return. Catch WWE action on ESPN, ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCJ5v_MCY6GNUBTO8-D3XoAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/DVeUoCsIEcc/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCi1yJWpplrbltQNmcfHs1IV7Mh-A",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/DVeUoCsIEcc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCV6YeTKqZKiHlCrI9z2Nt0qC3Yig",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "3rS83uI0Wak",
    title:
      "POPPY, AMY LEE, COURTNEY LAPLANTE - End of You (Official Music Video)",
    author: "SUMERIAN",
    number_of_views: 3258446,
    video_length: "3:26",
    description:
      "POPPY, AMY LEE, COURTNEY LAPLANTE // END OF YOU // OUT NOW Buy / Stream 'End of You': ...",
    is_live_content: null,
    published_time: "7 days ago",
    channel_id: "UCAtlZO9a52JIhQRyXDRLaZQ",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/3rS83uI0Wak/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmnpcJfKlWzIo-kcDxVJGTDHwgNA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/3rS83uI0Wak/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBNvUQNKkoSCCgQex3mUo6kw8SASw",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "tfxGelQZTEQ",
    title:
      "Holy F***, New Bruce Lee! Young Knockout Phenom - Asadula Imangazaliev",
    author: "VoteSport",
    number_of_views: 2388971,
    video_length: "14:30",
    description:
      "Graceful Asadula Imangazaliev stuns even sophisticated striking connoisseurs. With a multifaceted arsenal of attacks, the young ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UC5Y03h8JAslS5HEuvQNdVWw",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/tfxGelQZTEQ/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjMY5UzF2TwfwODLbTtZfMIrS2Hw",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/tfxGelQZTEQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdnRUn5X7jFBwShqVe5CIevCknwQ",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "z-zSgAAAG14",
    title:
      "FULL SEGMENT: AJ Lee and CM Punk challenge Becky Lynch and Seth Rollins: Raw, Sept. 8, 2025",
    author: "WWE",
    number_of_views: 2717842,
    video_length: "18:29",
    description:
      "AJ Lee returns to Raw to challenge Becky Lynch at Wrestlepalooza. Catch WWE action on ESPN, Netflix, Peacock, USA Network, ...",
    is_live_content: null,
    published_time: "3 days ago",
    channel_id: "UCJ5v_MCY6GNUBTO8-D3XoAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/z-zSgAAAG14/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCYvN_bNVWp4ewUQvo3bFIUgkUoyA",
        width: 480,
        height: 270,
      },
    ],
  },
  {
    video_id: "BjJkeSddTkI",
    title:
      "Backstage Footage Of AJ Lee Signing NEW WWE Contract Before SmackDown Return 😨 #wwe",
    author: "TheSportsEntertainer",
    number_of_views: 896032,
    video_length: "SHORTS",
    description:
      "Backstage Footage Of AJ Lee Signing NEW WWE Contract Before SmackDown Return #wwe Backstage footage of AJ Lee ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCPFYcLD2Po64A5fyq6WRwlA",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/BjJkeSddTkI/hq720.jpg?sqp=-oaymwE2COgCEMoBSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARheIF4oXjAP&rs=AOn4CLDVTb-5X0LNx1uJoS4rzWJcXJ2HoA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/BjJkeSddTkI/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARheIF4oXjAP&rs=AOn4CLCyFMJUTXoCpz_DuMRG4mHAoK4Jvw",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "hDvoG5Sl2NQ",
    title: "WWE - AJ Lee Custom Titantron (Entrance Video) 2025",
    author: "Luke Palacio",
    number_of_views: 185000,
    video_length: "2:59",
    description:
      "hello! -------------------------------------------------------------- •make sure to view in 1080p60• ⬇️⬇️⬇️ ◇SHE'S ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UC04EsgUmPH8bPwCNaqXz52Q",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/hDvoG5Sl2NQ/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqkYwh2Uhhz4zDKQdhncJNPVZOrA",
        width: 480,
        height: 270,
      },
    ],
  },
  {
    video_id: "f4EMyQRQjnw",
    title: "Bobby Hates Richie | Ep 286 | Bad Friends",
    author: "Bad Friends",
    number_of_views: 632289,
    video_length: "1:14:01",
    description:
      "Get MORE Bad Friends at our Patreon!! https://www.patreon.com/c/badfriends Thank you to our Sponsors: DraftKings, Kachava, ...",
    is_live_content: null,
    published_time: "3 days ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/f4EMyQRQjnw/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQML8pAkZrXG22jGap-jorwJqyXQ",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/f4EMyQRQjnw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA90Y4WAHUeYlrtDG0hv-QxSO5ghA",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "hWIcAnGKDzY",
    title:
      "FULL MATCH: CM Punk & AJ Lee vs. Daniel Bryan & Kane: Raw, June 11, 2012",
    author: "WWE Vault",
    number_of_views: 48934,
    video_length: "9:11",
    description:
      "WWE Champion CM Punk teams with AJ Lee as they take on Daniel Bryan and Kane in a unique matchup. Find the latest ...",
    is_live_content: null,
    published_time: "1 day ago",
    channel_id: "UCNSnSemXKDc9UEZ7m31wY9Q",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/hWIcAnGKDzY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDbg8AyUZ9NRmlGRDdTQ6gEwirFUg",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/hWIcAnGKDzY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDBsYiGFg3ILJzaw7SBFN7WCaTKXg",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "uXNQO5FpIFM",
    title: "Aj Lee Returns, Destroys Becky Lynch - WWE Smackdown 9/5/2025",
    author: "Matt Kempke",
    number_of_views: 59192,
    video_length: "1:12",
    description: "",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCfV8O1xhlB8O9YGz9ywmn8A",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/uXNQO5FpIFM/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBL4TqdUzJAjl_3yLguU5z1g2FvrA",
        width: 480,
        height: 270,
      },
    ],
  },
  {
    video_id: "y7ekbEOw_zg",
    title: "Don’t mess with AJ Lee’s man 😡😡😡 #WWERaw",
    author: "WWE",
    number_of_views: 557909,
    video_length: "SHORTS",
    description:
      "Where to watch WWE: https://wwe.com/wheretowatch Watch WWE on Netflix: http://netflix.com/WWE Watch WWE on ESPN: ...",
    is_live_content: null,
    published_time: "3 days ago",
    channel_id: "UCJ5v_MCY6GNUBTO8-D3XoAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/y7ekbEOw_zg/hq720.jpg?sqp=-oaymwE2COgCEMoBSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARhlIEsoQDAP&rs=AOn4CLAL6tpDq28dtJNE9duaNBBQZBW_BA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/y7ekbEOw_zg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARhlIEsoQDAP&rs=AOn4CLAvNB1ZQaTdtMUC9--Aw1QS1U2g9Q",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "CbfkD4jqSA4",
    title: "CHAOS 🤯 Adrian Lee vs. Tye Ruotolo | MMA | Highlights & Interview",
    author: "ONE Championship",
    number_of_views: 165473,
    video_length: "7:52",
    description:
      "All the madness from the highly anticipated lightweight mixed martial arts showdown between Adrian Lee and Tye Ruotolo!",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCiormkBf3jm6mfb7k0yPbKA",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/CbfkD4jqSA4/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqyyR0chRCUaxKre16AO8aF-magA",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/CbfkD4jqSA4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAPlRKxbxgYWE8k47NooquSEDEHkg",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "InzYZG3bUXc",
    title: "AJ LEE HAS RETURNED TO WWE!!!!!",
    author: "WWE",
    number_of_views: 4203046,
    video_length: "SHORTS",
    description:
      "Where to watch WWE: https://wwe.com/wheretowatch Watch WWE on Netflix: http://netflix.com/WWE Watch WWE on ESPN: ...",
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UCJ5v_MCY6GNUBTO8-D3XoAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/InzYZG3bUXc/hq720.jpg?sqp=-oaymwE2COgCEMoBSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhTIEgoZTAP&rs=AOn4CLDn4FgmisH9v2woHZSLkHyDAhESUg",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/InzYZG3bUXc/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhTIEgoZTAP&rs=AOn4CLAFW48CYpEoiPhBXbUriOWIDSVZyA",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "mzJ91D7FyCo",
    title:
      "🚨NEW🚨 Welcome to LEE! | Season 3 Story Trailer 👀 | LEGO NINJAGO: Dragons Rising",
    author: "LEGO",
    number_of_views: 359539,
    video_length: "1:26",
    description:
      "New story trailer alert for LEGO® NINJAGO®: Dragons Rising Season 3! Are you ready to enter the mysterious land of Lee ...",
    is_live_content: null,
    published_time: "3 weeks ago",
    channel_id: "UCP-Ng5SXUEt0VE-TXqRdL6g",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/mzJ91D7FyCo/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAxcl8LZ46Fayn3QSmd2f0byY1bUQ",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/mzJ91D7FyCo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnU2p1ajo9_HDzeCq2TG-ZaBWNlA",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "sh7-X5HX5OU",
    title: "WWE 2K25: Latest DLC Previews, 2K26 Legends Roster, AJ Lee & More!",
    author: "Smacktalks",
    number_of_views: 49765,
    video_length: "8:49",
    description:
      "Join us for the latest round-up of wrestling game news including the latest DLC previews for WWE 2K25, and an update on the ...",
    is_live_content: null,
    published_time: "5 days ago",
    channel_id: "UCAeTKI3Zcv44VDqq0koHy7Q",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/sh7-X5HX5OU/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC0oCSfFlRv3TvaK3hhN8NgKAjAiQ",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/sh7-X5HX5OU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB77e5RF9w47tvYO9QJ_FvXyR1lHg",
        width: 720,
        height: 404,
      },
    ],
  },
  {
    video_id: "NWHNRtWG-iM",
    title: "Spike Lee's newest movie",
    author: "CBS Mornings",
    number_of_views: 34886,
    video_length: "7:35",
    description:
      'Spike Lee\'s newest movie, "Highest 2 Lowest," stars his good friend, Denzel Washington. Lee sits down with "CBS Saturday ...',
    is_live_content: null,
    published_time: "6 days ago",
    channel_id: "UC-SJ6nODDmufqBzPBwCvYvQ",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/NWHNRtWG-iM/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDt46wkEcTZPOkjtKJN6PwoOP11aQ",
        width: 360,
        height: 202,
      },
      {
        url: "https://i.ytimg.com/vi/NWHNRtWG-iM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLConvdP1IFw9kJDqRs2-jIRPjZwDA",
        width: 720,
        height: 404,
      },
    ],
  },
];

export const videoData = [
  {
    itag: 18,
    url: "https://rr2---sn-gjo-w43s.googlevideo.com/videoplayback?expire=1757845763&ei=okTGaNXTDoiKkucP2rqGiQM&ip=156.237.40.215&id=o-AJv5g1h5C_e5vHGqrgZbyB6_6Eek32HMVubnxSW51Mk7&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=40&met=1757824162%2C&mh=Cx&mm=31%2C29&mn=sn-gjo-w43s%2Csn-ab5sznze&ms=au%2Crdu&mv=m&mvi=2&pl=22&rms=au%2Cau&initcwndbps=5230000&bui=AY1jyLNuJjAarbINO3ucU2MztPFKTSlwN6gO0azooq_rHc-LypC8k0x08iDZMMEZzQi8c2TUUmHTPTI9&spc=l3OVKTSiatux8MVukP5FR4dreFeyeOwcXkxzodLItSfT_XKweXXUI0KO4nBlCYNSc-UdYRXTyApgA_A7U6xesMb_&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Hk51asVNATMTkOjs3j79VpQQ&rqh=1&gir=yes&clen=157024223&ratebypass=yes&dur=1960.321&lmt=1756815602448289&mt=1757823691&fvip=3&fexp=51355912%2C51552689%2C51565116%2C51565682%2C51580968&c=WEB&sefc=1&txp=4538534&n=DpImIY9jRq4cWslDwDNd&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgRAgoTZfuX5uNikYVGzc3ATTZivWIdgP9vksVzHP7Vf4CIAWud7OCtY6txqYtxu4iypg0S6YKYQtVAYaelYA9x4hg&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRgIhALT4UmnXUsSSBMzWI_JDH5YC8uYcfE-Ckgof-FfX7aB-AiEAoGzcW81x5x3tf8ydm7nROkk0OVx0NQszcGtVdqNH4Q4%3D",
    mimeType: 'video/mp4; codecs="avc1.42001E, mp4a.40.2"',
    bitrate: 640828,
    width: 640,
    height: 360,
    lastModified: "1756815602448289",
    contentLength: "157024223",
    quality: "medium",
    fps: 30,
    qualityLabel: "360p",
    projectionType: "RECTANGULAR",
    averageBitrate: 640810,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960321",
    audioSampleRate: "44100",
    audioChannels: 2,
    qualityOrdinal: "QUALITY_ORDINAL_360P",
  },
  {
    itag: 313,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 17762357,
    width: 3840,
    height: 2160,
    initRange: {
      start: "0",
      end: "220",
    },
    indexRange: {
      start: "221",
      end: "6905",
    },
    lastModified: "1756803561862118",
    contentLength: "4129490450",
    quality: "hd2160",
    fps: 30,
    qualityLabel: "2160p",
    projectionType: "RECTANGULAR",
    averageBitrate: 16852767,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_2160P",
  },
  {
    itag: 401,
    mimeType: 'video/mp4; codecs="av01.0.12M.08"',
    bitrate: 16736204,
    width: 3840,
    height: 2160,
    initRange: {
      start: "0",
      end: "700",
    },
    indexRange: {
      start: "701",
      end: "5196",
    },
    lastModified: "1756792686275895",
    contentLength: "3477148043",
    quality: "hd2160",
    fps: 30,
    qualityLabel: "2160p",
    projectionType: "RECTANGULAR",
    averageBitrate: 14190515,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_2160P",
  },
  {
    itag: 271,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 8889328,
    width: 2560,
    height: 1440,
    initRange: {
      start: "0",
      end: "220",
    },
    indexRange: {
      start: "221",
      end: "6903",
    },
    lastModified: "1756798277188431",
    contentLength: "2024309169",
    quality: "hd1440",
    fps: 30,
    qualityLabel: "1440p",
    projectionType: "RECTANGULAR",
    averageBitrate: 8261361,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_1440P",
  },
  {
    itag: 400,
    mimeType: 'video/mp4; codecs="av01.0.12M.08"',
    bitrate: 7561437,
    width: 2560,
    height: 1440,
    initRange: {
      start: "0",
      end: "700",
    },
    indexRange: {
      start: "701",
      end: "5196",
    },
    lastModified: "1756791982840699",
    contentLength: "1604487264",
    quality: "hd1440",
    fps: 30,
    qualityLabel: "1440p",
    projectionType: "RECTANGULAR",
    averageBitrate: 6548038,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_1440P",
  },
  {
    itag: 137,
    mimeType: 'video/mp4; codecs="avc1.640028"',
    bitrate: 4340193,
    width: 1920,
    height: 1080,
    initRange: {
      start: "0",
      end: "741",
    },
    indexRange: {
      start: "742",
      end: "5249",
    },
    lastModified: "1756816714197035",
    contentLength: "808358831",
    quality: "hd1080",
    fps: 30,
    qualityLabel: "1080p",
    projectionType: "RECTANGULAR",
    averageBitrate: 3298976,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_1080P",
  },
  {
    itag: 248,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 2782233,
    width: 1920,
    height: 1080,
    initRange: {
      start: "0",
      end: "220",
    },
    indexRange: {
      start: "221",
      end: "6891",
    },
    lastModified: "1756795691082090",
    contentLength: "387943841",
    quality: "hd1080",
    fps: 30,
    qualityLabel: "1080p",
    projectionType: "RECTANGULAR",
    averageBitrate: 1583228,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_1080P",
  },
  {
    itag: 399,
    mimeType: 'video/mp4; codecs="av01.0.08M.08"',
    bitrate: 1740528,
    width: 1920,
    height: 1080,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756794932100815",
    contentLength: "351448227",
    quality: "hd1080",
    fps: 30,
    qualityLabel: "1080p",
    projectionType: "RECTANGULAR",
    averageBitrate: 1434287,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_1080P",
  },
  {
    itag: 136,
    mimeType: 'video/mp4; codecs="avc1.4d401f"',
    bitrate: 1035366,
    width: 1280,
    height: 720,
    initRange: {
      start: "0",
      end: "739",
    },
    indexRange: {
      start: "740",
      end: "5247",
    },
    lastModified: "1756815074028831",
    contentLength: "140033796",
    quality: "hd720",
    fps: 30,
    qualityLabel: "720p",
    projectionType: "RECTANGULAR",
    averageBitrate: 571488,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_720P",
  },
  {
    itag: 247,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 1453649,
    width: 1280,
    height: 720,
    initRange: {
      start: "0",
      end: "219",
    },
    indexRange: {
      start: "220",
      end: "6877",
    },
    lastModified: "1756796728098171",
    contentLength: "208308782",
    quality: "hd720",
    fps: 30,
    qualityLabel: "720p",
    projectionType: "RECTANGULAR",
    averageBitrate: 850124,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_720P",
  },
  {
    itag: 398,
    mimeType: 'video/mp4; codecs="av01.0.05M.08"',
    bitrate: 1170155,
    width: 1280,
    height: 720,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756793076759510",
    contentLength: "213324116",
    quality: "hd720",
    fps: 30,
    qualityLabel: "720p",
    projectionType: "RECTANGULAR",
    averageBitrate: 870592,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_720P",
  },
  {
    itag: 135,
    mimeType: 'video/mp4; codecs="avc1.4d401f"',
    bitrate: 647126,
    width: 854,
    height: 480,
    initRange: {
      start: "0",
      end: "740",
    },
    indexRange: {
      start: "741",
      end: "5248",
    },
    lastModified: "1756815791820811",
    contentLength: "89550748",
    quality: "large",
    fps: 30,
    qualityLabel: "480p",
    projectionType: "RECTANGULAR",
    averageBitrate: 365463,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_480P",
  },
  {
    itag: 244,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 832418,
    width: 854,
    height: 480,
    initRange: {
      start: "0",
      end: "219",
    },
    indexRange: {
      start: "220",
      end: "6854",
    },
    lastModified: "1756796738928088",
    contentLength: "113030034",
    quality: "large",
    fps: 30,
    qualityLabel: "480p",
    projectionType: "RECTANGULAR",
    averageBitrate: 461284,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_480P",
  },
  {
    itag: 397,
    mimeType: 'video/mp4; codecs="av01.0.04M.08"',
    bitrate: 666987,
    width: 854,
    height: 480,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756794181958255",
    contentLength: "119980001",
    quality: "large",
    fps: 30,
    qualityLabel: "480p",
    projectionType: "RECTANGULAR",
    averageBitrate: 489647,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_480P",
  },
  {
    itag: 134,
    mimeType: 'video/mp4; codecs="avc1.4d401e"',
    bitrate: 408054,
    width: 640,
    height: 360,
    initRange: {
      start: "0",
      end: "740",
    },
    indexRange: {
      start: "741",
      end: "5248",
    },
    lastModified: "1756815255323424",
    contentLength: "55071922",
    quality: "medium",
    fps: 30,
    qualityLabel: "360p",
    projectionType: "RECTANGULAR",
    averageBitrate: 224752,
    highReplication: true,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_360P",
  },
  {
    itag: 243,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 499734,
    width: 640,
    height: 360,
    initRange: {
      start: "0",
      end: "219",
    },
    indexRange: {
      start: "220",
      end: "6840",
    },
    lastModified: "1756796770269321",
    contentLength: "87247900",
    quality: "medium",
    fps: 30,
    qualityLabel: "360p",
    projectionType: "RECTANGULAR",
    averageBitrate: 356065,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_360P",
  },
  {
    itag: 396,
    mimeType: 'video/mp4; codecs="av01.0.01M.08"',
    bitrate: 331376,
    width: 640,
    height: 360,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756792273020055",
    contentLength: "58354147",
    quality: "medium",
    fps: 30,
    qualityLabel: "360p",
    projectionType: "RECTANGULAR",
    averageBitrate: 238147,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_360P",
  },
  {
    itag: 133,
    mimeType: 'video/mp4; codecs="avc1.4d4015"',
    bitrate: 202532,
    width: 426,
    height: 240,
    initRange: {
      start: "0",
      end: "739",
    },
    indexRange: {
      start: "740",
      end: "5247",
    },
    lastModified: "1756816056038828",
    contentLength: "26756930",
    quality: "small",
    fps: 30,
    qualityLabel: "240p",
    projectionType: "RECTANGULAR",
    averageBitrate: 109197,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_240P",
  },
  {
    itag: 242,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 233545,
    width: 426,
    height: 240,
    initRange: {
      start: "0",
      end: "218",
    },
    indexRange: {
      start: "219",
      end: "6739",
    },
    lastModified: "1756796750428112",
    contentLength: "35064796",
    quality: "small",
    fps: 30,
    qualityLabel: "240p",
    projectionType: "RECTANGULAR",
    averageBitrate: 143102,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_240P",
  },
  {
    itag: 395,
    mimeType: 'video/mp4; codecs="av01.0.00M.08"',
    bitrate: 142326,
    width: 426,
    height: 240,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756791185853784",
    contentLength: "25252893",
    quality: "small",
    fps: 30,
    qualityLabel: "240p",
    projectionType: "RECTANGULAR",
    averageBitrate: 103059,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_240P",
  },
  {
    itag: 160,
    mimeType: 'video/mp4; codecs="avc1.4d400c"',
    bitrate: 88748,
    width: 256,
    height: 144,
    initRange: {
      start: "0",
      end: "738",
    },
    indexRange: {
      start: "739",
      end: "5246",
    },
    lastModified: "1756815275227389",
    contentLength: "11531362",
    quality: "tiny",
    fps: 30,
    qualityLabel: "144p",
    projectionType: "RECTANGULAR",
    averageBitrate: 47060,
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_144P",
  },
  {
    itag: 278,
    mimeType: 'video/webm; codecs="vp9"',
    bitrate: 118195,
    width: 256,
    height: 144,
    initRange: {
      start: "0",
      end: "218",
    },
    indexRange: {
      start: "219",
      end: "6565",
    },
    lastModified: "1756796717082197",
    contentLength: "18179515",
    quality: "tiny",
    fps: 30,
    qualityLabel: "144p",
    projectionType: "RECTANGULAR",
    averageBitrate: 74191,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960267",
    qualityOrdinal: "QUALITY_ORDINAL_144P",
  },
  {
    itag: 394,
    mimeType: 'video/mp4; codecs="av01.0.00M.08"',
    bitrate: 83323,
    width: 256,
    height: 144,
    initRange: {
      start: "0",
      end: "699",
    },
    indexRange: {
      start: "700",
      end: "5195",
    },
    lastModified: "1756791182113804",
    contentLength: "16232703",
    quality: "tiny",
    fps: 30,
    qualityLabel: "144p",
    projectionType: "RECTANGULAR",
    averageBitrate: 66246,
    colorInfo: {
      primaries: "COLOR_PRIMARIES_BT709",
      transferCharacteristics: "COLOR_TRANSFER_CHARACTERISTICS_BT709",
      matrixCoefficients: "COLOR_MATRIX_COEFFICIENTS_BT709",
    },
    approxDurationMs: "1960266",
    qualityOrdinal: "QUALITY_ORDINAL_144P",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132352,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339685430090",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVkZS1ERQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "German (DE)",
      id: "de-DE.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.7199993,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132276,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339586618509",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVlcy1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Spanish (US)",
      id: "es-US.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.5,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132342,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339593167459",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVmci1GUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "French (FR)",
      id: "fr-FR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132269,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339618380462",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJoaQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Hindi",
      id: "hi.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.2299995,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132247,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339606132308",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpZA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Indonesian",
      id: "id.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.33,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132296,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339612589986",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpdA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Italian",
      id: "it.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.2999992,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132314,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339610626753",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJqYQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Japanese",
      id: "ja.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.3099995,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132426,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339647145007",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJwbA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Polish",
      id: "pl.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -1.75,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132311,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756339758161906",
    contentLength: "31727197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVwdC1CUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Portuguese (BR)",
      id: "pt-BR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960367",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.3700008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 140,
    mimeType: 'audio/mp4; codecs="mp4a.40.2"',
    bitrate: 132322,
    initRange: {
      start: "0",
      end: "722",
    },
    indexRange: {
      start: "723",
      end: "3118",
    },
    lastModified: "1756347828116777",
    contentLength: "31726446",
    quality: "tiny",
    xtags: "ChEKBWFjb250EghvcmlnaW5hbAoNCgRsYW5nEgVlbi1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "English (US) original",
      id: "en-US.4",
      audioIsDefault: true,
    },
    averageBitrate: 129474,
    highReplication: true,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960321",
    audioSampleRate: "44100",
    audioChannels: 2,
    loudnessDb: -2.1200008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 64144,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339691471293",
    contentLength: "13645185",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVkZS1ERQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "German (DE)",
      id: "de-DE.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 55684,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.7299995,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 64443,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756340258450558",
    contentLength: "13599389",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVlcy1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Spanish (US)",
      id: "es-US.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 55498,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.5,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 65041,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339721647907",
    contentLength: "14012847",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVmci1GUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "French (FR)",
      id: "fr-FR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 57185,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 64528,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339814677699",
    contentLength: "13557342",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJoaQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Hindi",
      id: "hi.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 55326,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 66012,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339728833951",
    contentLength: "14498375",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpZA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Indonesian",
      id: "id.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 59166,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3400002,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 64591,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339716849239",
    contentLength: "14159915",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpdA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Italian",
      id: "it.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 57785,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2999992,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 64042,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339755696257",
    contentLength: "14301239",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJqYQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Japanese",
      id: "ja.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 58362,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3199997,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 67339,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339750670347",
    contentLength: "13708671",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJwbA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Polish",
      id: "pl.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 55944,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -1.75,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 63893,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3604",
    },
    lastModified: "1756339738818559",
    contentLength: "13703216",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVwdC1CUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Portuguese (BR)",
      id: "pt-BR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 55921,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3700008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 249,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 63475,
    initRange: {
      start: "0",
      end: "265",
    },
    indexRange: {
      start: "266",
      end: "3611",
    },
    lastModified: "1756348045967591",
    contentLength: "13755131",
    quality: "tiny",
    xtags: "ChEKBWFjb250EghvcmlnaW5hbAoNCgRsYW5nEgVlbi1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "English (US) original",
      id: "en-US.4",
      audioIsDefault: true,
    },
    averageBitrate: 56134,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960301",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.1200008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 83024,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3617",
    },
    lastModified: "1756339691496618",
    contentLength: "17724644",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVkZS1ERQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "German (DE)",
      id: "de-DE.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 72332,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.7299995,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 83339,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3616",
    },
    lastModified: "1756340258784674",
    contentLength: "17589590",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVlcy1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Spanish (US)",
      id: "es-US.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 71781,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.5,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 84449,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3621",
    },
    lastModified: "1756339721752202",
    contentLength: "18104197",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVmci1GUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "French (FR)",
      id: "fr-FR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 73881,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 83493,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3615",
    },
    lastModified: "1756339814644301",
    contentLength: "17532122",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJoaQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Hindi",
      id: "hi.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 71547,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 85956,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3628",
    },
    lastModified: "1756339728849043",
    contentLength: "18806425",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpZA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Indonesian",
      id: "id.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 76747,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3400002,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 83477,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3623",
    },
    lastModified: "1756339716922541",
    contentLength: "18329639",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpdA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Italian",
      id: "it.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 74801,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2999992,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 82799,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3625",
    },
    lastModified: "1756339755699955",
    contentLength: "18468703",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJqYQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Japanese",
      id: "ja.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 75369,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3199997,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 86292,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3617",
    },
    lastModified: "1756339750666993",
    contentLength: "17748460",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJwbA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Polish",
      id: "pl.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 72430,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -1.75,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 82739,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3617",
    },
    lastModified: "1756339738783536",
    contentLength: "17739503",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVwdC1CUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Portuguese (BR)",
      id: "pt-BR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 72393,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3700008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 250,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 82975,
    initRange: {
      start: "0",
      end: "265",
    },
    indexRange: {
      start: "266",
      end: "3628",
    },
    lastModified: "1756348045985760",
    contentLength: "18028564",
    quality: "tiny",
    xtags: "ChEKBWFjb250EghvcmlnaW5hbAoNCgRsYW5nEgVlbi1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "English (US) original",
      id: "en-US.4",
      audioIsDefault: true,
    },
    averageBitrate: 73574,
    audioQuality: "AUDIO_QUALITY_LOW",
    approxDurationMs: "1960301",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.1200008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 158389,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3706",
    },
    lastModified: "1756339691592691",
    contentLength: "34369220",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVkZS1ERQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "German (DE)",
      id: "de-DE.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 140258,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.7299995,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 156048,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3705",
    },
    lastModified: "1756340258390300",
    contentLength: "33948285",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVlcy1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Spanish (US)",
      id: "es-US.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 138540,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.5,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 163674,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3707",
    },
    lastModified: "1756339721759159",
    contentLength: "35027342",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVmci1GUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "French (FR)",
      id: "fr-FR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 142943,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 155296,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3703",
    },
    lastModified: "1756339814638536",
    contentLength: "33628997",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJoaQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Hindi",
      id: "hi.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 137237,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2399998,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 167600,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3711",
    },
    lastModified: "1756339728841580",
    contentLength: "36423417",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpZA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Indonesian",
      id: "id.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 148641,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3400002,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 160037,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3708",
    },
    lastModified: "1756339716865803",
    contentLength: "35298024",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJpdA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Italian",
      id: "it.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 144048,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.2999992,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 159263,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3708",
    },
    lastModified: "1756339755737899",
    contentLength: "35326393",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJqYQ",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Japanese",
      id: "ja.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 144164,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3199997,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 160530,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3705",
    },
    lastModified: "1756339750628690",
    contentLength: "34233113",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoKCgRsYW5nEgJwbA",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Polish",
      id: "pl.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 139702,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -1.75,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 155015,
    initRange: {
      start: "0",
      end: "258",
    },
    indexRange: {
      start: "259",
      end: "3705",
    },
    lastModified: "1756339738814697",
    contentLength: "34048157",
    quality: "tiny",
    xtags: "ChQKBWFjb250EgtkdWJiZWQtYXV0bwoNCgRsYW5nEgVwdC1CUg",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "Portuguese (BR)",
      id: "pt-BR.10",
      audioIsDefault: false,
      isAutoDubbed: true,
    },
    averageBitrate: 138947,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960341",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.3700008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
  {
    itag: 251,
    mimeType: 'audio/webm; codecs="opus"',
    bitrate: 163109,
    initRange: {
      start: "0",
      end: "265",
    },
    indexRange: {
      start: "266",
      end: "3715",
    },
    lastModified: "1756348045981724",
    contentLength: "35648117",
    quality: "tiny",
    xtags: "ChEKBWFjb250EghvcmlnaW5hbAoNCgRsYW5nEgVlbi1VUw",
    projectionType: "RECTANGULAR",
    audioTrack: {
      displayName: "English (US) original",
      id: "en-US.4",
      audioIsDefault: true,
    },
    averageBitrate: 145480,
    audioQuality: "AUDIO_QUALITY_MEDIUM",
    approxDurationMs: "1960301",
    audioSampleRate: "48000",
    audioChannels: 2,
    loudnessDb: -2.1200008,
    qualityOrdinal: "QUALITY_ORDINAL_UNKNOWN",
  },
];
